#!/bin/dash
for dest; do :; done

for file in "$@"; do
	if [ "$file" != "$dest" ]; then
		rsync -a --delete --filter=". $HOME/backup/filter" "$file" "$dest"
		sync
		msg="In $(pwd): backed up and synced $file to $dest"
		notify-send -u low "backup-file" "$msg"
		echo $msg
	fi
done
