#!/bin/dash

while getopts "u:" option
do
	case $option in
		u) username=$OPTARG ;;
	esac
done

stty -echo
read -p "Enter passphrase: " passphrase
echo
stty echo
read -p "Enter site: " site

passwords=$(gpg -d --batch --passphrase $passphrase $HOME/Documents/passwords.gpg 2> /dev/null)
correct_site=0
should_print=0

while read line; do
	if [ "$line" = "[$site]" ]; then
		correct_site=1
	fi
	if [ $correct_site -ne 1 ]; then
		continue
	fi
	if [ -z $line ]; then
		break
	fi

	if [ "$line" = "Username:" ]; then
		prev_line=$line
		continue
	fi
	if [ "$prev_line" = "Username:" ]; then
		if [ -z "$username" -o "$line" = "$username" ]; then
			echo $prev_line
			should_print=1
		else
			should_print=0
			continue
		fi
	fi

	if [ $should_print -eq 1 ]; then
		if [ "$prev_line" = "Password:" ]; then
			echo $line | xclip -sel clipboard
			echo "Password copied to clipboard"
		else
			echo $line
		fi
	fi

	prev_line=$line
done << EOF
$passwords
EOF
