#!/bin/dash
read -p "Enter passphrase: " passphrase
read -p "Enter site: " site
passwords=$(gpg -d --batch --passphrase $passphrase $HOME/Documents/passwords.gpg)
while read line; do
    if [ "$line" = "[$site]" ]; then
        should_print="yes"
    fi
    if [ "$should_print" = "yes" ]; then
        if [ "$line" = "Password:" ]; then
            should_print=
            is_password="yes"
        else
            echo $line
        fi
    elif [ "$is_password" = "yes" ]; then
        is_password=
        echo $line | xclip -sel clipboard
        echo "Password copied to clipboard"
    fi
done << EOF
$passwords
EOF
