#!/bin/zsh

threads=6

while getopts "T:" option
do
    case $option in
        T) threads=$OPTARG ;;
    esac
done

PASSWORD_STORE_CLIP_TIME=1 pass -c OpenBench/normal
password=$(xclip -o -sel clipboard)

cd $HOME/coding/repositories/OpenBench/Client
[ -f /opt/miniconda3/etc/profile.d/conda.sh ] && source /opt/miniconda3/etc/profile.d/conda.sh
conda activate openbench
python client.py -U Beanie -P $password -S http://localhost:8000 -T $threads -N 1 &
wait
conda deactivate
rm openbench.exit
