#!/bin/zsh

cd $HOME/coding/repositories/OpenBench
[ -f /opt/miniconda3/etc/profile.d/conda.sh ] && source /opt/miniconda3/etc/profile.d/conda.sh
conda activate openbench
python manage.py runserver 0:8000
conda deactivate
