#!/bin/dash
date=$(date '+%Y-%m-%d_%H-%M-%S')
sprt_dir=/home/Beanie/coding/sprt

cutechess-cli \
    -engine name=$1 proto=uci cmd=$1 \
    -engine name=$2 proto=uci cmd=$2 \
    -each tc=8+0.08 \
    -variant standard \
    -concurrency 12 \
    -sprt elo0=0 elo1=5 alpha=0.05 beta=0.05 \
    -games 2 -rounds 5000 -repeat 2 \
    -openings file=$sprt_dir/UHO_XXL_2022_+110_+139.epd format=epd order=random \
    -pgnout $sprt_dir/$date.pgn
    #-debug \
    #-draw movenumber=40 movecount=3 score=10 \
    #-resign movecount=3 score=400 \
