#!/bin/dash
date=$(date '+%Y-%m-%d_%H-%M-%S')
sprt_dir=$HOME/coding/sprt
use_engine_names=0
root_dir=.

tc=8+0.08
variant=standard
concurrency=8
elo0=0
elo1=5
sprt_cmd="-sprt elo0=$elo0 elo1=$elo1 alpha=0.05 beta=0.05"
rounds=5000
rating_interval=250
opening_file=$sprt_dir/UHO_XXL_2022_+110_+139.epd

die() {
	# don't delete the given engines if we're not using branches
	if [ $use_engine_names -eq 1 ]; then
		exit 0
	fi

	if [ -n $branch ]; then
		git checkout $branch
	fi

	if [ -n $new -a -e $sprt_dir/$new ]; then
		rm -f $sprt_dir/$new
	fi
	if [ -n $base -a -e $sprt_dir/$base ]; then
		rm -f $sprt_dir/$base
	fi

	exit 0
}

help() {
	echo "sprt - a simple wrapper over \`cutechess-cli\` to run SPRTs."
	echo "Usage: sprt [-c <threads>] [-e] [-h] [-r <root_dir>]"
	echo "            <git branch> | <engine 1> <engine 2>"
	echo ""
	echo "Options:"
	echo "    -c <threads>"
	echo "        Run <threads> games in parallel."
	echo "    -e"
	echo "        Compare <engine 1> against <engine 2>. Default is to compare"
	echo "        <git branch> against master in <root_dir>."
	echo "    -h"
	echo "        Show this message."
	echo "    -r <root_dir>"
	echo "        Set the root directory for the two engines or git branch to"
	echo "        this path. Default is the current directory."
	echo "    -s"
	echo "        Use simplification bounds (elo0 = -5, elo1 = 0)."
	echo "    -t <rounds>"
	echo "        Don't run an SPRT; just run a fixed-round test. Each round"
	echo "        has two games so divide the desired rounds by 2."
	exit 0
}

# exit cleanly when Ctrl+C'd
trap die 2

while getopts "c:ehr:st:" option
do
	case $option in
		c) concurrency=$OPTARG ;;
		e) use_engine_names=1 ;;
		h) help ;;
		r) root_dir=$OPTARG ;;
		s)
			elo0=-5
			elo1=0
			;;
		t)
			rounds=$OPTARG
			sprt_cmd=
			;;
	esac
done

shift $(($OPTIND - 1))

if [ $use_engine_names -eq 1 ]; then
	new=$1
	new_cmd=$root_dir/$new
	base=$2
	base_cmd=$root_dir/$base
else
	branch=$(git branch --show-current)
	new=$1
	new_cmd=$sprt_dir/$new
	base=master
	base_cmd=$sprt_dir/$base
	cd $root_dir
	git checkout $1
	cargo build --release
	mv -f $root_dir/target/release/crab $sprt_dir/$new
	git checkout master
	cargo build --release
	mv -f $root_dir/target/release/crab $sprt_dir/$base
fi

cutechess-cli \
	-engine name=$new proto=uci cmd=$new_cmd \
	-engine name=$base proto=uci cmd=$base_cmd \
	-each tc=$tc \
	-variant $variant \
	-concurrency $concurrency \
	$sprt_cmd \
	-games 2 -rounds $rounds -repeat 2 \
	-ratinginterval $rating_interval \
	-openings file=$opening_file format=epd order=random \
	-pgnout $sprt_dir/$date.pgn \
	-resign movecount=3 score=300 \
	-draw movenumber=40 movecount=3 score=10
	#-debug

die
